table dim_rooms
	lineageTag: fdc7a57b-fca5-46e0-bfe8-00e310382920

	column room_id
		dataType: string
		lineageTag: 83200e5d-93ad-4084-97fe-38521da991cc
		summarizeBy: none
		sourceColumn: room_id

		annotation SummarizationSetBy = Automatic

	column room_class
		dataType: string
		lineageTag: d65ea015-2d0a-43c4-aee2-d50a4b30fd30
		summarizeBy: none
		sourceColumn: room_class

		annotation SummarizationSetBy = Automatic

	partition dim_rooms = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("F:\DATA_ANALYST BOOTCAMP\Power BI\Resume_Project_Challenge\Hospitalitiy\input-files-1\Input Files\dim_rooms.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Used first row as headers" = Table.TransformColumnTypes(#"Promoted Headers",{{"room_id", type text}, {"room_class", type text}})
				in
				    #"Used first row as headers"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

